name: 🐛 Bug Report
description: Submit a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our bug report form 🙏

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 👟 Reproduction steps
      description: How do you trigger this bug? Please walk us through it step by step.
      placeholder: When I ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 👍 Expected behavior
      description: What did you think would happen?
      placeholder: It should ...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 👎 Actual Behavior
      description: What did actually happen? Add screenshots, if applicable.
      placeholder: It actually ...
    validations:
      required: true
