name: 🚀 Feature
description: Submit a proposal for a new feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our feature request form 🙏

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A clear and concise description of what the feature is.
      placeholder: You should add ...
    validations:
      required: true

  - type: textarea
    id: pitch
    attributes:
      label: 🎤 Pitch
      description: Please explain why this feature should be implemented and how it would be used. Add examples, if applicable.
      placeholder: In my use-case, ...
    validations:
      required: true
